# Generated by Django 5.2.4 on 2025-08-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Principal', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('archivo_timbrado', models.FileField(help_text='Archivo PNG del timbrado oficial', upload_to='configuracion_impresion/timbrado/')),
                ('firma_doctor', models.ImageField(help_text='Imagen PNG de la firma del doctor', upload_to='configuracion_impresion/firmas/')),
                ('sello_clinica', models.ImageField(help_text='Imagen PNG del sello de la clínica', upload_to='configuracion_impresion/sellos/')),
                ('max_elementos_por_impresion', models.PositiveIntegerField(default=3, help_text='Máximo número de elementos por impresión')),
                ('nombre_clinica', models.CharField(blank=True, max_length=200)),
                ('direccion_clinica', models.TextField(blank=True)),
                ('telefono_clinica', models.CharField(blank=True, max_length=50)),
                ('email_clinica', models.EmailField(blank=True, max_length=254)),
                ('margen_superior', models.PositiveIntegerField(default=20, help_text='Margen superior en mm')),
                ('margen_inferior', models.PositiveIntegerField(default=20, help_text='Margen inferior en mm')),
                ('margen_izquierdo', models.PositiveIntegerField(default=20, help_text='Margen izquierdo en mm')),
                ('margen_derecho', models.PositiveIntegerField(default=20, help_text='Margen derecho en mm')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Impresión',
                'verbose_name_plural': 'Configuraciones de Impresión',
                'ordering': ['-activo', '-creado_en'],
            },
        ),
    ]
