# Generated by Django 5.2.4 on 2025-08-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('paciente', 'Paciente'), ('doctor', 'Doctor'), ('asistente', 'Asistente')], default='paciente', max_length=20),
        ),
    ]
