# Generated by Django 5.2.4 on 2025-08-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='doctores.doctorperfil')),
            ],
            options={
                'ordering': ['doctor', 'dia_semana', 'hora_inicio'],
                'unique_together': {('doctor', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
