# Generated by Django 5.2.4 on 2025-08-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_horariodoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodoctor',
            name='intervalo_minutos',
            field=models.PositiveIntegerField(default=30, help_text='Duración de cada cita en minutos para este día/horario'),
        ),
    ]
