# Generated by Django 5.2.4 on 2025-08-07 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0003_horariodoctor_intervalo_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('capacidad', models.PositiveIntegerField(default=1, help_text='Número máximo de pacientes que puede atender simultáneamente')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='horariodoctor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='horariodoctor',
            name='consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='doctores.consultorio'),
        ),
        migrations.AlterUniqueTogether(
            name='horariodoctor',
            unique_together={('doctor', 'consultorio', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
    ]
