# Generated by Django 5.2.4 on 2025-08-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinfo',
            name='mision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='nosotros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='valores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
