# Generated by Django 5.2.4 on 2025-08-02 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacientePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20)),
                ('alergias', models.TextField(blank=True)),
                ('enfermedades_cronicas', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('antecedentes_quirurgicos', models.TextField(blank=True)),
                ('antecedentes_familiares', models.TextField(blank=True)),
                ('seguro_medico', models.CharField(blank=True, max_length=100)),
                ('numero_seguro', models.CharField(blank=True, max_length=100)),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('estado_civil', models.CharField(blank=True, max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('completado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
