# Generated by Django 5.2.4 on 2025-08-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteperfil',
            name='identificacion',
            field=models.CharField(blank=True, help_text='Cédula, DNI, Pasaporte, etc.', max_length=50, verbose_name='Número de Identificación'),
        ),
    ]
