# Generated by Django 5.2.4 on 2025-08-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_pacienteperfil_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteperfil',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union_libre', 'Unión libre'), ('separado', 'Separado/a')], max_length=20),
        ),
    ]
