# Generated by Django 5.2.4 on 2025-08-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('doctores', '0004_consultorio_alter_horariodoctor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cita',
            name='consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='doctores.consultorio'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('doctor', 'consultorio', 'fecha', 'hora_inicio', 'hora_fin')},
        ),
    ]
